### ISSUE TITLE
[Feat]  Legend UI 기능연결 - 스킬 쿨타임

### ISSUE THREAD

**Issue by wave-sound** [KIA-PROGRAMMING-38/Team_ItaCH_SmashLegends#104]
# 설명
Legend UI에 기능을 연결합니다.
- 스킬의 재사용 대기시간에 따라 그 크기가 변하는 스킬 게이지바를 구현합니다.
- 참고자료 및 주의사항은 #101 과 동일합니다.

#270 구현 이후 진행합니다.

**Comment by stalepatt** [comment]
기획 변경으로 미개발
