### ISSUE TITLE
[Feature]피터 피격시 체공 구현

### ISSUE THREAD

**Issue by gitLeejw** [KIA-PROGRAMMING-38/Team_ItaCH_SmashLegends#112]
# 설명
- 애니메이터 오류 수정

# 참고자료
관련된 기획서 혹은 이슈 등의 링크를 답니다.
- [문서1](링크)
- [문서2](링크)
- [문서3](링크)

# 주의사항
기능을 개발할 때 주의사항에 대해서 작성합니다.

**Comment by lees5402** [comment]
담당자 이진우 -> 이찬혁 변경
