### ISSUE TITLE
[Feat] Mode UI 기능 연결 - 궁극기 사용가능 여부

### ISSUE THREAD

**Issue by wave-sound** [KIA-PROGRAMMING-38/Team_ItaCH_SmashLegends#161]
# 설명
모드 UI에 캐릭터의 궁극기 사용여부를 알려주는 기능을 추가합니다.
해당 UI에 빛이 나는 효과를 추가합니다.

# 참고자료
- [문서1](https://docs.google.com/document/d/15cBiHx_j-4FW9uq__iq7rMsXC_dWaF5MgRND-SSiNDQ/edit?usp=drivesdk)

# 주의사항
#270 구현 이후 진행합니다.

**Comment by stalepatt** [comment]
기획 변경으로 쿨타임 미개발
