### ISSUE TITLE
[Feature] 피터 스킬 공격 이펙트 추가 

### ISSUE THREAD

**Issue by gitLeejw** [KIA-PROGRAMMING-38/Team_ItaCH_SmashLegends#168]
# 설명
피터의 스킬 공격시 이펙트가 출력됩니다.

# 참고자료
관련된 기획서 혹은 이슈 등의 링크를 답니다.
- [문서1](링크)
- [문서2](링크)
- [문서3](링크)

# 주의사항
기능을 개발할 때 주의사항에 대해서 작성합니다.

**Comment by stalepatt** [comment]
현재 문서 링크가 이상합니다. PR 페이지로 이동 되어서 확인 부탁드립니다. 문서1 문서2 같은 내용보다 해당 링크를 설명할 수 있는 단어로 표현하면 좋을 것 같습니다
