### ISSUE TITLE
[Feature] 전체 캐릭터 헤비공격 쿨타임 구현

### ISSUE THREAD

**Issue by gitLeejw** [KIA-PROGRAMMING-38/Team_ItaCH_SmashLegends#270]
# 설명
현재 각 캐릭터가 헤비공격시 쿨타임이 존재하지않아 무한정 공격이 가능한 점을 보완합니다.
쿨타임을 적용하여 해당 쿨타임이 지난 후 사용할 수 있도록 구현합니다.

**Comment by stalepatt** [comment]
기획 변경으로 쿨타임 미구현
