### ISSUE TITLE
[Bug] 인게임 씬 캐릭터 HP Box 오류

### ISSUE THREAD

**Issue by gitLeejw** [KIA-PROGRAMMING-38/Team_ItaCH_SmashLegends#312]
# 설명
캐릭터의 체력을 나타내는 UI 중 Box Assign 오류로 인한 이슈 입니다.

# 오류 내용
![image](https://github.com/KIA-PROGRAMMING-38/Team_ItaCH_SmashLegends/assets/118022787/204a0d62-b30e-4b58-b0fa-f5ed5b524555)
![image](https://github.com/KIA-PROGRAMMING-38/Team_ItaCH_SmashLegends/assets/118022787/ddc447b2-12bd-42e6-a43f-f61575848379)

**Comment by stalepatt** [comment]
플레이어 연결 이슈 해결 이후 발생하지 않습니다. 향후 다시 발생하는 경우 Reopen 해서 참고합니다
