### ISSUE TITLE
[Feature] 엘리스 헤비공격 모션 이펙트 구현

### ISSUE THREAD

**Issue by gitLeejw** [KIA-PROGRAMMING-38/Team_ItaCH_SmashLegends#317]
# 설명
엘리스가 헤비공격을 실시 할 때 던지는 이펙트, 먼지 이펙트 를 구현합니다.

# 참고자료
관련된 기획서 혹은 이슈 등의 링크를 답니다.
![image](https://github.com/KIA-PROGRAMMING-38/Team_ItaCH_SmashLegends/assets/118022787/3b2a1dec-bb3f-4af1-811e-1b2dea4c71f9)

# 주의사항
기능을 개발할 때 주의사항에 대해서 작성합니다.

**Comment by stalepatt** [comment]
상황봐서 필요하면 재오픈
