### ISSUE TITLE
[Bug] 엘리스 헤비공격중 발생하는 Null Reference 오류를 수정합니다.

### ISSUE THREAD

**Issue by gitLeejw** [KIA-PROGRAMMING-38/Team_ItaCH_SmashLegends#318]
# 설명
Alice Bomb 스크립트의 CS : 79 라인에서 발생하는 NRE 오류를 수정합니다.

# 재현하기
1. 엘리스 헤비공격 입력
2. 헤비공격이 적 캐릭터 에게 닿았을시 NRE
# 참고자료
관련된 기획서 혹은 이슈 등의 링크를 답니다.
- [관련 이슈](https://github.com/KIA-PROGRAMMING-38/Team_ItaCH_SmashLegends/issues/209)

**Comment by stalepatt** [comment]
현재 해당 이슈 Effect 비동기 작업에서 발생한 것까지 확인

**Comment by stalepatt** [comment]
공격 판정 시 데이터를 넘겨주는 부분에서 초기화된 데미지 데이터에서 NRE 확인
