### ISSUE TITLE
[Bug] 엘리스 공격중 행상태 돌입시 이펙트 잔존 오류 

### ISSUE THREAD

**Issue by gitLeejw** [KIA-PROGRAMMING-38/Team_ItaCH_SmashLegends#320]
# 설명
엘리스가 공격중 Hang 상태에 돌입할때 기존에 실시하던 이펙트가 잔존하는 오류를 수정합니다.

# 참고자료

![image](https://github.com/KIA-PROGRAMMING-38/Team_ItaCH_SmashLegends/assets/118022787/9f02b80c-6e24-40c4-ada1-f1b38e536416)

![image](https://github.com/KIA-PROGRAMMING-38/Team_ItaCH_SmashLegends/assets/118022787/9de909eb-4015-4943-9e6e-a6e6652941ae)

# 재현하기

1.엘리스 공격실행중 Hang 상태 돌입하기

**Comment by stalepatt** [comment]
확인 결과 실제 게임과 셰이더 크기 차이로 보이는 착시 현상
실제 게임에서는 이펙트 전부 재생 이후 Hang으로 진입하여 #316  Hang 관련 이슈 수정하면서 재확인 필요
