### ISSUE TITLE
[Bug] 후크 Skill Attack 관련 버그

### ISSUE THREAD

**Issue by stalepatt** [KIA-PROGRAMMING-38/Team_ItaCH_SmashLegends#332]
# 테스트 환경
- OS : Win11
- CPU : i7-12700H
- GPU : RTX 3060 Laptop
- Mode : Editor

# 설명
- 후크 스킬 어택 사용 시 총 오브젝트가 바닥에 떨어지는 현상이 발생합니다.
- 더불어 Bullet 관련 NRE 가 발생합니다.

# 재현하기
1. 에디터에서 Lobby 씬으로 게임 실행
2. 후크 캐릭터 선택
3. InGame 씬에서 1P 기준 '/' 버튼으로 스킬 어택 실행 

# 스크린샷
![image](https://github.com/KIA-PROGRAMMING-38/Team_ItaCH_SmashLegends/assets/120005138/becb5117-da64-41c9-8940-192b361ea3aa)
![image](https://github.com/KIA-PROGRAMMING-38/Team_ItaCH_SmashLegends/assets/120005138/dcc9e935-d009-4423-865a-c646636b66a8)
![HookBug_AdobeExpress](https://github.com/KIA-PROGRAMMING-38/Team_ItaCH_SmashLegends/assets/120005138/64f9d8af-2e8a-4f3f-8098-669c77d9821a)
![hookbug2_AdobeExpress](https://github.com/KIA-PROGRAMMING-38/Team_ItaCH_SmashLegends/assets/120005138/6ae40791-3b2c-4792-a8fb-967363897d19)

**Comment by gitLeejw** [comment]
원작 게임 애니메이션의 형태입니다.
카메라 조정이후 부자연스러울 시 애니메이션 직접 수정 필요합니다.
