### ISSUE TITLE
[Bug] Alice HeavyAttack 사용 중 위치 지정 오류 현상

### ISSUE THREAD

**Issue by stalepatt** [KIA-PROGRAMMING-38/Team_ItaCH_SmashLegends#345]
# 테스트 환경
테스트를 진행한 환경을 알려주세요.
- OS : Win11
- CPU : i7-12700H
- GPU : RTX 3060 Laptop
- Mode : Editor

# 설명
Alice 캐릭터로 Heavy Attack 사용 시 지면에 닿기 전에 플레이어가 이동한다면 Bomb 오브젝트도 함께 움직입니다.

# 재현하기
버그 발생 상황을 단계별로 설명해주세요.
1. Alice  캐릭터 선택 후 게임 실행
2. Heavy Attack 사용 이후 bomb 오브젝트가 지면에 닿기 전에 플레이어 방향 전환

# 스크린샷
![HeavyAttack_EndPoint_AdobeExpress](https://github.com/KIA-PROGRAMMING-38/Team_ItaCH_SmashLegends/assets/120005138/a0750c57-8703-4888-928a-a7eb1b77f4cf)

**Comment by gitLeejw** [comment]
#406
