### ISSUE TITLE
[Feature] ResourceManager 리팩토링

### ISSUE THREAD

**Issue by stalepatt** [KIA-PROGRAMMING-38/Team_ItaCH_SmashLegends#356]
# 설명
- ResourceManager의 리팩토링을 진행합니다.

# 참고자료

- [리소스 매니저 구조](https://docs.google.com/spreadsheets/d/11NEf2xE77z6a-yw7jRjo15-pPM_sXzvX8PGvucLZYR4/edit#gid=1760026416)

**Comment by lees5402** [comment]
Resoures에서 따로 경로를 정해주지 않고 필요할 때 마다 직접 사용하면 될 것 같다 라는 의견
