### ISSUE TITLE
[Feat] 범용 이펙트 개발

### ISSUE THREAD

**Issue by wave-sound** [KIA-PROGRAMMING-38/Team_ItaCH_SmashLegends#51]
# 설명
게임 내부에서 사용되는 범용 이펙트를 개발합니다.
범용 이펙트에는 피격 이펙트, 스매시 이펙트, 체력 회복 이펙트가 있습니다.
이펙트의 이름은 명시적으로 작성합니다.

# 주의사항
풀 리퀘스트시, 해당 이펙트의 이름을 명시합니다.

**Comment by stalepatt** [comment]
day2에 merge 완
