### ISSUE TITLE
[Docs] 미니게임 기획서 작성

### ISSUE THREAD

**Issue by kcs9608** [KIA-PROGRAMMING-38/Team_ItaCH_SmashLegends#52]
# 설명
- Smash Legend에 들어갈 미니게임을 기획합니다.
- 3종류의 게임을 기획했습니다.
- SmashUp (창작)
- ZigZag (모작)
- StackBall (모작)

# 참고자료
- [ZigZag](https://www.youtube.com/shorts/SRLUS88DZqo)
- [StackBall](https://www.youtube.com/shorts/CJU2e0ppRIA)
- [미니 게임 기획 및 하이퍼 캐주얼 게임 분석](https://docs.google.com/document/d/18kWZ6U4c9suq5e0bW6snakOkcpx6cZXLCA6qDr3bkL0/edit#)

**Comment by stalepatt** [comment]
아래에 Comment로 완성된 자료 링크나 상태 남겨주세요.
이슈에 설명 좀 더 적어주세요.

**Comment by kcs9608** [comment]
[미니 게임 기획 및 하이퍼 캐주얼 게임 분석](https://docs.google.com/document/d/18kWZ6U4c9suq5e0bW6snakOkcpx6cZXLCA6qDr3bkL0/edit#)

**Comment by stalepatt** [comment]
문서 제목 변경하였습니다. 내일 교수님 피드백 이후 Issue Close 하겠습니다.

**Comment by kcs9608** [comment]
확인했습니다

**Comment by stalepatt** [comment]
해당 기획에 대한 개발 중단으로 이슈 종료
