### ISSUE TITLE
[Docs] 캐릭터 보이스 네이밍 컨벤션 문서 작성 및 해당 컨벤션 적용

### ISSUE THREAD

**Issue by wave-sound** [KIA-PROGRAMMING-38/Team_ItaCH_SmashLegends#76]
# 설명
캐릭터의 목소리가 담긴 사운드 파일에 대한 네이밍 컨벤션을 문서로 작성합니다.
해당 네이밍 컨벤션을 적용합니다.

# 참고자료
- [문서1] https://docs.google.com/document/d/1RlG7MkkCKSF_mP7W3yD_PLyl3kXOl_wGRs8pC_4MxHY/edit

# 주의사항
효과음(SFX) 및 배경음(BGM)은 직관적이기에 따로 변경하지 않고, 필요 시 추후 다른 이슈에서 해결합니다.

**Comment by wave-sound** [comment]
https://drive.google.com/file/d/177dNHbJWv9ej2zkUfP0cl_x_6s6ojqcL/view?usp=drive_link 작업 완료한 소리 파일 모음입니다.

**Comment by stalepatt** [comment]
확인했습니다. Close 하겠습니다.
