### ISSUE TITLE
[Docs] 사운드 매니저 설계

### ISSUE THREAD

**Issue by wave-sound** [KIA-PROGRAMMING-38/Team_ItaCH_SmashLegends#82]
# 설명
게임 내의 소리를 담당하는 매니저 클래스인 사운드 매니저를 설계합니다.

# 주의사항
사운드는 종류 별로 그 음성 크기를 조절할 수 있어야 합니다.

**Comment by stalepatt** [comment]
규칙에 대한 상세 기술 보충 필요

**Comment by stalepatt** [comment]
확인 완료
